version: "3.9"
services:
  node-app:
    build: .
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      # - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:14rc1-alpine
    env_file: .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
