version: "3.0"

services:
  db:
    image: postgres:14rc1-alpine
    restart: unless-stopped
    container_name: integration-tests-prisma
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
